### ISSUE TITLE
Spring Integration

### ISSUE THREAD

**Issue by smullins3000** [meirwah/awesome-workflow-engines#25]
It seems like Spring Integration (https://spring.io/projects/spring-integration) should be added to this list. It has state machine, message buses, etc. that would appear to put it in this category.

**Comment by rsoika** [comment]
I do not agree with this idea. Users looking on the site are searching for workflow engines and not things having a workflow-like behavior. If we do so, somebody can add the 'Docker Workflow', the 'Maven Workflow', ant-scripts and so on...
Spring is an framework for application-architecture, similar to Jakarta EE too and also Microsoft .Net

I would like to define a workflow-engine in the way as described on [Wikipedia](https://en.wikipedia.org/wiki/Workflow_engine).

**Comment by smullins3000** [comment]
You should take a look at the site. I think it fits the definition of
enterprise workflow.

**Comment by meirwah** [comment]
Yes, I agree with @rsoika on this point, closing.. sorry @smullins3000
