### ISSUE TITLE
Activate "Github Pages" for this project

### ISSUE THREAD

**Issue by rsoika** [meirwah/awesome-workflow-engines#26]
since some time github provides a new feature where you can transform the readme file into a web page

https://meirwah.github.io/awesome-workflow-engines/

This can be activated in : Settings -> Github Pages -> Source = Master Branch

I think this is a nice feature to have a separate web page for your project?
See also [here](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages)

**Comment by meirwah** [comment]
done, thanks for the suggestion !
