### ISSUE TITLE
Missing Lyft's Flyte

### ISSUE THREAD

**Issue by austinkeller** [meirwah/awesome-workflow-engines#46]
Announced a few days ago: https://eng.lyft.com/introducing-flyte-cloud-native-machine-learning-and-data-processing-platform-fb2bb3046a59

**Comment by austinkeller** [comment]
The platform is an engine written in Go with a Python SDK that seems to be the primary interface for writing workflows/tasks.

**Comment by meirwah** [comment]
plz create a PR to add this according to contribution guidelines @austinkeller

**Comment by kumare3** [comment]
Thank you for bringing this up @austinkeller. Please let me know if you can add it, or should I create a PR?

**Comment by kumare3** [comment]
@meirwah I just created the PR actually - https://github.com/meirwah/awesome-workflow-engines/pull/53
