### ISSUE TITLE
Add Workflow Core

### ISSUE THREAD

**Issue by reyronald** [meirwah/awesome-workflow-engines#9]
> Workflow Core is a light weight workflow engine targeting .NET Standard. Think: long running processes with multiple tasks that need to track state. It supports pluggable persistence and concurrency providers to allow for multi-node clusters.

https://github.com/danielgerlag/workflow-core

**Comment by meirwah** [comment]
@reyronald feel free to open a PR to add this

**Comment by kinow** [comment]
This can be closed as the PR has been merged already.
